# Generated by Django 6.1.1 on 2026-09-28 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_title',
            field=models.CharField(default='Nameless', max_length=200),
        ),
    ]
